In [1]:
# !pip install pyarrow

In [1]:
import pandas as pd
from statistics import mode

In [2]:
df = pd.read_parquet('sleep.parquet')

In [3]:
df.head(20)

,Start,End,Sleep quality,Time in bed,Wake up,Sleep Notes,Heart rate,Activity (steps)
0,2014-12-29 22:57:49,2014-12-30 07:30:13,100%,8:32,:),None,59.0,0
1,2014-12-30 21:17:50,2014-12-30 21:33:54,3%,0:16,:|,Stressful day,72.0,0
2,2014-12-30 22:42:49,2014-12-31 07:13:31,98%,8:30,:|,None,57.0,0
3,2014-12-31 22:31:01,2015-01-01 06:03:01,65%,7:32,None,None,NaN,0
4,2015-01-01 22:12:10,2015-01-02 04:56:35,72%,6:44,:),Drank coffee:Drank tea,68.0,0
5,2015-01-03 00:34:57,2015-01-03 07:47:23,83%,7:12,:),Drank coffee:Drank tea,60.0,0
6,2015-01-04 00:23:06,2015-01-04 07:37:09,78%,7:14,None,Drank tea,NaN,0
7,2015-01-04 21:34:44,2015-01-05 04:53:34,78%,7:18,:),Ate late:Drank coffee,57.0,0
8,2015-01-05 21:32:25,2015-01-06 05:00:03,69%,7:27,:),Drank coffee:Drank tea:Worked out,56.0,0
9,2015-01-06 21:24:56,2015-01-07 05:00:02,74%,7:35,:|,Drank tea:Worked out,64.0,0
10,2015-01-07 20:59:58,2015-01-08 06:19:20,81%,9:19,:),Drank coffee:Drank tea:Stressful day,62.0,0
11,2015-01-08 22:58:18,2015-01-09 06:14:58,88%,7:16,:),Drank coffee:Drank tea,58.0,0
12,2015-01-09 22:27:58,2015-01-10 07:29:00,77%,9:01,:|,Drank coffee:Drank tea,65.0,0
13,2015-01-10 22:38:24,2015-01-11 07:28:59,89%,8:50,:|,Drank coffee:Drank tea,65.0,0
14,2015-01-11 22:12:07,2015-01-12 06:20:29,78%,8:08,:),Drank tea,53.0,0
15,2015-01-12 21:01:46,2015-01-13 06:13:23,100%,9:11,:),Drank tea:Worked out,65.0,0
16,2015-01-13 22:14:29,2015-01-14 06:20:33,100%,8:06,:),Drank coffee:Drank tea,55.0,0
17,2015-01-14 21:48:26,2015-01-15 05:02:05,88%,7:13,:),Drank coffee:Drank tea:Worked out,60.0,0
18,2015-01-15 21:32:07,2015-01-16 04:54:42,87%,7:22,:),Drank tea,60.0,0
19,2015-01-17 02:11:57,2015-01-17 09:03:37,83%,6:51,:),Drank coffee:Drank tea,94.0,0

In [4]:
df["Sleep Notes"].unique()

array([None, 'Stressful day', 'Drank coffee:Drank tea', 'Drank tea',
       'Ate late:Drank coffee', 'Drank coffee:Drank tea:Worked out',
       'Drank tea:Worked out', 'Drank coffee:Drank tea:Stressful day',
       'Drank coffee', 'Drank coffee:Drank tea:Stressful day:Worked out',
       'Drank coffee:Worked out', 'Ate late:Drank coffee:Drank tea',
       'Ate late:Drank coffee:Drank tea:Worked out',
       'Drank tea:Stressful day', 'Drank tea:Stressful day:Worked out',
       'Drank coffee:Stressful day:Worked out',
       'Drank coffee:Stressful day',
       'Ate late:Drank coffee:Drank tea:Stressful day', 'Worked out',
       'Ate late:Drank coffee:Worked out'], dtype=object)

In [5]:
df.head(20)

,Start,End,Sleep quality,Time in bed,Wake up,Sleep Notes,Heart rate,Activity (steps)
0,2014-12-29 22:57:49,2014-12-30 07:30:13,100%,8:32,:),None,59.0,0
1,2014-12-30 21:17:50,2014-12-30 21:33:54,3%,0:16,:|,Stressful day,72.0,0
2,2014-12-30 22:42:49,2014-12-31 07:13:31,98%,8:30,:|,None,57.0,0
3,2014-12-31 22:31:01,2015-01-01 06:03:01,65%,7:32,None,None,NaN,0
4,2015-01-01 22:12:10,2015-01-02 04:56:35,72%,6:44,:),Drank coffee:Drank tea,68.0,0
5,2015-01-03 00:34:57,2015-01-03 07:47:23,83%,7:12,:),Drank coffee:Drank tea,60.0,0
6,2015-01-04 00:23:06,2015-01-04 07:37:09,78%,7:14,None,Drank tea,NaN,0
7,2015-01-04 21:34:44,2015-01-05 04:53:34,78%,7:18,:),Ate late:Drank coffee,57.0,0
8,2015-01-05 21:32:25,2015-01-06 05:00:03,69%,7:27,:),Drank coffee:Drank tea:Worked out,56.0,0
9,2015-01-06 21:24:56,2015-01-07 05:00:02,74%,7:35,:|,Drank tea:Worked out,64.0,0
10,2015-01-07 20:59:58,2015-01-08 06:19:20,81%,9:19,:),Drank coffee:Drank tea:Stressful day,62.0,0
11,2015-01-08 22:58:18,2015-01-09 06:14:58,88%,7:16,:),Drank coffee:Drank tea,58.0,0
12,2015-01-09 22:27:58,2015-01-10 07:29:00,77%,9:01,:|,Drank coffee:Drank tea,65.0,0
13,2015-01-10 22:38:24,2015-01-11 07:28:59,89%,8:50,:|,Drank coffee:Drank tea,65.0,0
14,2015-01-11 22:12:07,2015-01-12 06:20:29,78%,8:08,:),Drank tea,53.0,0
15,2015-01-12 21:01:46,2015-01-13 06:13:23,100%,9:11,:),Drank tea:Worked out,65.0,0
16,2015-01-13 22:14:29,2015-01-14 06:20:33,100%,8:06,:),Drank coffee:Drank tea,55.0,0
17,2015-01-14 21:48:26,2015-01-15 05:02:05,88%,7:13,:),Drank coffee:Drank tea:Worked out,60.0,0
18,2015-01-15 21:32:07,2015-01-16 04:54:42,87%,7:22,:),Drank tea,60.0,0
19,2015-01-17 02:11:57,2015-01-17 09:03:37,83%,6:51,:),Drank coffee:Drank tea,94.0,0

In [6]:
empty_rows_count = df.isnull().sum()

In [7]:
empty_rows_count

Start                 0
End                   0
Sleep quality         0
Time in bed           0
Wake up             641
Sleep Notes         235
Heart rate          725
Activity (steps)      0
dtype: int64

In [8]:
most_frequent_wakeup = df['Wake up'].mode().iloc[0]
most_frequent_value = df['Sleep Notes'].mode().iloc[0]
mean_heart_rate = df['Heart rate'].mean()

In [9]:
df['Wake up'].fillna(value=most_frequent_wakeup, inplace=True)
df['Sleep Notes'].fillna(value=most_frequent_value, inplace=True)
df['Heart rate'].fillna(value=mean_heart_rate, inplace=True)

In [10]:
empty_rows_count = df.isnull().sum()
empty_rows_count

Start               0
End                 0
Sleep quality       0
Time in bed         0
Wake up             0
Sleep Notes         0
Heart rate          0
Activity (steps)    0
dtype: int64

In [11]:
mask = df['Sleep Notes'].str.contains('Stressful day', case=False)
mask_worked_out = df['Sleep Notes'].str.contains('Worked out', case=False)
mask_drank_coffee = df['Sleep Notes'].str.contains('Drank coffee', case=False)
mask_drank_tea = df['Sleep Notes'].str.contains('Drank tea', case=False)
mask_ate_late = df['Sleep Notes'].str.contains('Ate late', case=False)

In [14]:
df['Stressful day'] = False 
df.loc[mask, 'Stressful day'] = True
df['Worked out'] = False
df.loc[mask_worked_out, 'Worked out'] = True

df['Drank coffee'] = False
df.loc[mask_drank_coffee, 'Drank coffee'] = True

df['Drank tea'] = False
df.loc[mask_drank_tea, 'Drank tea'] = True

df['Ate late'] = False
df.loc[mask_ate_late, 'Ate late'] = True

In [15]:
df['Start'] = pd.to_datetime(df['Start'])
df['End'] = pd.to_datetime(df['End'])

In [16]:
df['Duration'] = df['End'] - df['Start']

In [17]:
df['Duration'] = df['Duration'].dt.components['hours'].astype(str).str.zfill(2) + ':' + \
                df['Duration'].dt.components['minutes'].astype(str).str.zfill(2) + ':' + \
                df['Duration'].dt.components['seconds'].astype(str).str.zfill(2)

In [17]:
df.head(20)

,Start,End,Sleep quality,Time in bed,Wake up,Sleep Notes,Heart rate,Activity (steps),Stressful day,Worked out,Drank coffee,Drank tea,Ate late,Duration
0,2014-12-29 22:57:49,2014-12-30 07:30:13,100%,8:32,:),Drank coffee:Drank tea:Worked out,59.000000,0,False,True,True,True,False,08:32:24
1,2014-12-30 21:17:50,2014-12-30 21:33:54,3%,0:16,:|,Stressful day,72.000000,0,True,False,False,False,False,00:16:04
2,2014-12-30 22:42:49,2014-12-31 07:13:31,98%,8:30,:|,Drank coffee:Drank tea:Worked out,57.000000,0,False,True,True,True,False,08:30:42
3,2014-12-31 22:31:01,2015-01-01 06:03:01,65%,7:32,:),Drank coffee:Drank tea:Worked out,60.604938,0,False,True,True,True,False,07:32:00
4,2015-01-01 22:12:10,2015-01-02 04:56:35,72%,6:44,:),Drank coffee:Drank tea,68.000000,0,False,False,True,True,False,06:44:25
5,2015-01-03 00:34:57,2015-01-03 07:47:23,83%,7:12,:),Drank coffee:Drank tea,60.000000,0,False,False,True,True,False,07:12:26
6,2015-01-04 00:23:06,2015-01-04 07:37:09,78%,7:14,:),Drank tea,60.604938,0,False,False,False,True,False,07:14:03
7,2015-01-04 21:34:44,2015-01-05 04:53:34,78%,7:18,:),Ate late:Drank coffee,57.000000,0,False,False,True,False,True,07:18:50
8,2015-01-05 21:32:25,2015-01-06 05:00:03,69%,7:27,:),Drank coffee:Drank tea:Worked out,56.000000,0,False,True,True,True,False,07:27:38
9,2015-01-06 21:24:56,2015-01-07 05:00:02,74%,7:35,:|,Drank tea:Worked out,64.000000,0,False,True,False,True,False,07:35:06
10,2015-01-07 20:59:58,2015-01-08 06:19:20,81%,9:19,:),Drank coffee:Drank tea:Stressful day,62.000000,0,True,False,True,True,False,09:19:22
11,2015-01-08 22:58:18,2015-01-09 06:14:58,88%,7:16,:),Drank coffee:Drank tea,58.000000,0,False,False,True,True,False,07:16:40
12,2015-01-09 22:27:58,2015-01-10 07:29:00,77%,9:01,:|,Drank coffee:Drank tea,65.000000,0,False,False,True,True,False,09:01:02
13,2015-01-10 22:38:24,2015-01-11 07:28:59,89%,8:50,:|,Drank coffee:Drank tea,65.000000,0,False,False,True,True,False,08:50:35
14,2015-01-11 22:12:07,2015-01-12 06:20:29,78%,8:08,:),Drank tea,53.000000,0,False,False,False,True,False,08:08:22
15,2015-01-12 21:01:46,2015-01-13 06:13:23,100%,9:11,:),Drank tea:Worked out,65.000000,0,False,True,False,True,False,09:11:37
16,2015-01-13 22:14:29,2015-01-14 06:20:33,100%,8:06,:),Drank coffee:Drank tea,55.000000,0,False,False,True,True,False,08:06:04
17,2015-01-14 21:48:26,2015-01-15 05:02:05,88%,7:13,:),Drank coffee:Drank tea:Worked out,60.000000,0,False,True,True,True,False,07:13:39
18,2015-01-15 21:32:07,2015-01-16 04:54:42,87%,7:22,:),Drank tea,60.000000,0,False,False,False,True,False,07:22:35
19,2015-01-17 02:11:57,2015-01-17 09:03:37,83%,6:51,:),Drank coffee:Drank tea,94.000000,0,False,False,True,True,False,06:51:40

In [18]:
df.to_parquet('sleep_new.parquet', index=False)